//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using SmartStringResources;


namespace SPAFirst.Resources.Strings {
    
    
    /// <summary>
    ///   Provides access to string resources.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SmartStringResources", "1.2.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class Buttons {
        
        /// <summary>
        ///   Looks up a localized string similar to: About
        /// </summary>
        public static string About([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::SPAFirst.Resources.Buttons.About;
            }
            return global::SPAFirst.Resources.Buttons.ResourceManager.GetString("About", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Back To List
        /// </summary>
        public static string Back([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::SPAFirst.Resources.Buttons.Back;
            }
            return global::SPAFirst.Resources.Buttons.ResourceManager.GetString("Back", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Create
        /// </summary>
        public static string Create([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::SPAFirst.Resources.Buttons.Create;
            }
            return global::SPAFirst.Resources.Buttons.ResourceManager.GetString("Create", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Create New
        /// </summary>
        public static string CreateNew([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::SPAFirst.Resources.Buttons.CreateNew;
            }
            return global::SPAFirst.Resources.Buttons.ResourceManager.GetString("CreateNew", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Delete
        /// </summary>
        public static string Delete([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::SPAFirst.Resources.Buttons.Delete;
            }
            return global::SPAFirst.Resources.Buttons.ResourceManager.GetString("Delete", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Details
        /// </summary>
        public static string Details([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::SPAFirst.Resources.Buttons.Details;
            }
            return global::SPAFirst.Resources.Buttons.ResourceManager.GetString("Details", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Edit
        /// </summary>
        public static string Edit([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::SPAFirst.Resources.Buttons.Edit;
            }
            return global::SPAFirst.Resources.Buttons.ResourceManager.GetString("Edit", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Forms
        /// </summary>
        public static string Forms([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::SPAFirst.Resources.Buttons.Forms;
            }
            return global::SPAFirst.Resources.Buttons.ResourceManager.GetString("Forms", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Home
        /// </summary>
        public static string Home([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::SPAFirst.Resources.Buttons.Home;
            }
            return global::SPAFirst.Resources.Buttons.ResourceManager.GetString("Home", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: People
        /// </summary>
        public static string People([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::SPAFirst.Resources.Buttons.People;
            }
            return global::SPAFirst.Resources.Buttons.ResourceManager.GetString("People", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: People List
        /// </summary>
        public static string PeopleList([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::SPAFirst.Resources.Buttons.PeopleList;
            }
            return global::SPAFirst.Resources.Buttons.ResourceManager.GetString("PeopleList", resourceCulture);
        }
    }
}
namespace SPAFirst.Resources.Strings {
    
    
    /// <summary>
    ///   Provides access to string resource keys.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SmartStringResources", "1.2.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class ButtonsKeys {
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: About
        /// </summary>
        public const string About = "About";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Back To List
        /// </summary>
        public const string Back = "Back";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Create
        /// </summary>
        public const string Create = "Create";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Create New
        /// </summary>
        public const string CreateNew = "CreateNew";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Delete
        /// </summary>
        public const string Delete = "Delete";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Details
        /// </summary>
        public const string Details = "Details";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Edit
        /// </summary>
        public const string Edit = "Edit";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Forms
        /// </summary>
        public const string Forms = "Forms";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Home
        /// </summary>
        public const string Home = "Home";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: People
        /// </summary>
        public const string People = "People";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: People List
        /// </summary>
        public const string PeopleList = "PeopleList";
    }
}
