//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using SmartStringResources;


namespace SPAFirst.Resources.Strings {
    
    
    /// <summary>
    ///   Provides access to string resources.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SmartStringResources", "1.2.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class Messages {
        
        /// <summary>
        ///   Looks up a localized string similar to: Admin
        /// </summary>
        public static string AdminTitle([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::SPAFirst.Resources.Messages.AdminTitle;
            }
            return global::SPAFirst.Resources.Messages.ResourceManager.GetString("AdminTitle", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: First Name
        /// </summary>
        public static string FirstName([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::SPAFirst.Resources.Messages.FirstName;
            }
            return global::SPAFirst.Resources.Messages.ResourceManager.GetString("FirstName", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Is Active
        /// </summary>
        public static string IsActive([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::SPAFirst.Resources.Messages.IsActive;
            }
            return global::SPAFirst.Resources.Messages.ResourceManager.GetString("IsActive", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Last Name
        /// </summary>
        public static string LastName([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::SPAFirst.Resources.Messages.LastName;
            }
            return global::SPAFirst.Resources.Messages.ResourceManager.GetString("LastName", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Person
        /// </summary>
        public static string Person([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::SPAFirst.Resources.Messages.Person;
            }
            return global::SPAFirst.Resources.Messages.ResourceManager.GetString("Person", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Person List
        /// </summary>
        public static string PersonList([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::SPAFirst.Resources.Messages.PersonList;
            }
            return global::SPAFirst.Resources.Messages.ResourceManager.GetString("PersonList", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: The {0} Is Required.Please Fill It
        /// </summary>
        public static string Required(object arg0, [System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return SmartStringResources.StringFormatWithExtension.FormatWith(global::SPAFirst.Resources.Messages.Required, System.Tuple.Create("0", arg0));
            }
            return SmartStringResources.StringFormatWithExtension.FormatWith(global::SPAFirst.Resources.Messages.ResourceManager.GetString("Required", resourceCulture), System.Tuple.Create("0", arg0));
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: The {0} Must Declare between {1} and {2}
        /// </summary>
        public static string StringLength(object arg0, object arg1, object arg2, [System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return SmartStringResources.StringFormatWithExtension.FormatWith(global::SPAFirst.Resources.Messages.StringLength, System.Tuple.Create("0", arg0), System.Tuple.Create("1", arg1), System.Tuple.Create("2", arg2));
            }
            return SmartStringResources.StringFormatWithExtension.FormatWith(global::SPAFirst.Resources.Messages.ResourceManager.GetString("StringLength", resourceCulture), System.Tuple.Create("0", arg0), System.Tuple.Create("1", arg1), System.Tuple.Create("2", arg2));
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: Title
        /// </summary>
        public static string Title([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::SPAFirst.Resources.Messages.Title;
            }
            return global::SPAFirst.Resources.Messages.ResourceManager.GetString("Title", resourceCulture);
        }
        
        /// <summary>
        ///   Looks up a localized string similar to: User
        /// </summary>
        public static string UserTitle([System.Runtime.InteropServices.OptionalAttribute()] System.Globalization.CultureInfo resourceCulture) {
            if (object.ReferenceEquals(resourceCulture, null)) {
                return global::SPAFirst.Resources.Messages.UserTitle;
            }
            return global::SPAFirst.Resources.Messages.ResourceManager.GetString("UserTitle", resourceCulture);
        }
    }
}
namespace SPAFirst.Resources.Strings {
    
    
    /// <summary>
    ///   Provides access to string resource keys.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SmartStringResources", "1.2.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class MessagesKeys {
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Admin
        /// </summary>
        public const string AdminTitle = "AdminTitle";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: First Name
        /// </summary>
        public const string FirstName = "FirstName";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Is Active
        /// </summary>
        public const string IsActive = "IsActive";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Last Name
        /// </summary>
        public const string LastName = "LastName";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Person
        /// </summary>
        public const string Person = "Person";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Person List
        /// </summary>
        public const string PersonList = "PersonList";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: The {0} Is Required.Please Fill It
        /// </summary>
        public const string Required = "Required";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: The {0} Must Declare between {1} and {2}
        /// </summary>
        public const string StringLength = "StringLength";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: Title
        /// </summary>
        public const string Title = "Title";
        
        /// <summary>
        ///   Provides access to string resource key of value similar to: User
        /// </summary>
        public const string UserTitle = "UserTitle";
    }
}
